extends:
  - react-app
  - standard
  - plugin:jsx-a11y/recommended
plugins:
  - import
  - jsx-a11y
  - promise
  - react
  - standard
rules:
  import/newline-after-import: [2, 2]
  import/order: 2
  object-curly-spacing: 2
  jsx-a11y/label-has-for: 0
  padded-blocks: [error, classes: always]
  react/jsx-uses-vars: 1
  space-before-function-paren: [error, never]
